### ISSUE TITLE
Исправить прозрачное наложение страниц при переходах

### ISSUE THREAD

**Issue by roketstorm** [DmitrDomrachev/photos#5]
При переходе на детальные страницы происходит наложение контента.
Нужно, чтобы страницы не сливались при переходах.

![Запись экрана 2023-06-22 в 15 44 02](https://github.com/DmitrDomrachev/photos/assets/18070124/598d8605-dd6e-4016-a079-a9355937bfb9)

**Comment by DmitrDomrachev** [comment]
Закрыта, так как повторяет https://github.com/DmitrDomrachev/photos/issues/4. Наложение из-за прозрачного фона.
